name: Deploy to AWS

on:
  workflow_dispatch:  # Manually trigger the workflow from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Allow GitHub to generate an OIDC token

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::510278866235:role/OIDC2
          aws-region: us-east-1  # Set your AWS region

      - name: Initialize Terraform
        run: |
          cd terraform  # Change to your Terraform directory
          terraform init  # Initialize Terraform configuration

      - name: Plan Terraform Deployment
        run: |
          cd terraform  # Change to your Terraform directory
          terraform plan  # Plan the deployment

      - name: Apply Terraform Deployment
        run: |
          cd terraform  # Change to your Terraform directory
          terraform apply -auto-approve  # Apply the deployment without approval
