name: Deploy to AWS

on:
  workflow_dispatch:  # Manually trigger the workflow from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Allow GitHub to generate an OIDC token

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::510278866235:role/OIDC2
          aws-region: us-east-1  # Set your AWS region

      - name: Install Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo tee /etc/apt/trusted.gpg.d/hashicorp.asc
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update -y
          sudo apt-get install -y terraform

      - name: Terraform Init
        run: terraform init
        working-directory: terraform  # Ensure Terraform runs from the correct directory

      - name: Terraform Plan
        run: terraform plan 
        working-directory: terraform  # Ensure Terraform runs from the correct directory

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform  # Ensure Terraform runs from the correct directory
